- setup.py
Put in a check to make sure that the python executable matches the installed science tools.  Doesn't do this check if the SLAC tools are detected.   Here's the code: 
```python
#Check to make sure we're using the python in the STs.
if os.environ.has_key('GLAST_EXT'):
print "Looks like you're using the SLAC version of the tools."
print "Not checking for correct python."
elif os.environ.has_key('FERMI_DIR'):
print "Looks like you're using the FSSC version of the tools."
fermi_dir = os.getenv('FERMI_DIR')
os_file = os.__file__
if fermi_dir not in os_file:
print "Python executable is not the one in $FERMI_DIR/bin.  Exiting."
sys.exit(1)
else:
print "Looks like the Fermi Science Tools are not setup.  Exiting."
sys.exit(1)```
> setup.py tests for correct python

- fermipy/castro.py
- fermipy/fits_utils.py
- fermipy/gtanalysis.py
- fermipy/hpx_utils.py
- fermipy/plotting.py
- fermipy/residmap.py
- fermipy/scripts/clone_configs.py
- fermipy/scripts/cluster_sources.py
- fermipy/scripts/collect_sources.py
- fermipy/scripts/dispatch.py
- fermipy/sed.py
- fermipy/skymap.py
- fermipy/sourcefind.py
- fermipy/srcmap_utils.py
- fermipy/stats_utils.py
- fermipy/tests/test_castro.py
- fermipy/tests/test_gtanalysis.py
- fermipy/tsmap.py
- fermipy/utils.py
- fermipy/wcs_utils.py
This PR removes unused imports.
This is a first tiny step towards making it easier to see which module in Fermipy depends on which other module, with the end goal of being able to extract things like `hpx_utils` and `skymap`.
> Remove unused imports

- fermipy/sourcefind.py
- fermipy/utils.py
This is an attempt to fix this SyntaxError on Python 3
```
$ python -c 'import fermipy.utils'
No module named 'version'
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/deil/code/fermipy/fermipy/utils.py", line 493
def parabola((x, y), amplitude, x0, y0, sx, sy, theta):
^
SyntaxError: invalid syntax
```
A small step towards making import work on Python 3 (see #42)
@woodmd  - Please have a look. I'm not sure if this code is under test or if this fix is correct.
> Fix parabola function call for Python 3

- .travis.yml
- README.rst
- fermipy/tests/coveragerc
We should add test coverage measure, to see which parts of Fermipy are completely untested.
It's easy to do with [pytest-cov](https://pypi.python.org/pypi/pytest-cov):
```
pip install pytest-cov
py.test -vv -s --cov=fermipy
```
Adding a test coverage report online is also useful and pretty easy.
- Activate https://coveralls.io/
- Add some lines to travis-ci to pip install `pytest-cov`, `coveralls` and submit the coverage command via a command like [this](https://github.com/gammapy/gammapy/blob/master/.travis.yml#L177)
- Add a badge to the README like [this](https://github.com/astropy/astropy/blame/master/README.rst#L38) so that it's visible and easy to find the link
- Disable coverage commenting on pull requests. (most devs find this annoying, checking this is something maintainers do …
> Test coverage

- fermipy/utils.py
This PR adds a `init_matplotlib_backend` function to the `utils` module that can be used to set the matplotlib backend.  If a DISPLAY is not detected then the backend is set to `Agg`.  Otherwise the function will set the backend with the string provided in the `backend` argument.  The recommended usage for this function is to call it at the top of one's analysis script but *before* importing any other fermipy modules, e.g.
```
from fermipy import utils
utils.init_matplotlib_backend()
from fermipy.gtanalysis import GTAnalysis
```
> Matplotlib backend fix

- fermipy/gtanalysis.py
This is a bug fix for the `optimize` method.  The `skip_sources` list was being incorrectly filled with names of sources that were fit in the first optimization step.
> Fix logic for skipping sources in optimize().

- fermipy/__init__.py
- fermipy/scripts/cluster_sources.py
I always get this message:
```
$ python -c 'import fermipy'
No module named 'version'
```
@woodmd - Do you know why that is and how to fix it? Or should I have a look?
> No module named version

- fermipy/spectrum.py
- fermipy/tests/test_spectrum.py
This PR implements a pure-python version of DMFitFunction which can be used with a `CastroData` or `TSCube` class to perform spectral fits of various DM models.
> Adding first implementation of dmfitfunction class.

- fermipy/castro.py
- fermipy/gtanalysis.py
- fermipy/sed_plotting.py
- fermipy/utils.py
This PR fixes the calculation of two-sided intervals in `CastroData`.  Previously the `LnLFn` was using the `getLimit` function to solve for both parameter limits and intervals.  The new implementation now uses separate delta-loglikelihood thresholds for limits and intervals calculated with `utils.onesided_cl_to_dlnl` and `utils.twosided_cl_to_dlnl`.  The function `getDeltaLogLike` is used to solve for the coordinate that corresponds a given change in the log-likelihood value in both cases.
> Changes in castro to fix confidence interval calculation.

- fermipy/castro.py
- fermipy/spectrum.py
- fermipy/tests/test_castro.py
- fermipy/tests/test_spectrum.py
This PR simplifies the interface for performing spectral fits with a `CastroData` object and allows `fit_spectrum` to be more easily used with `DMFitFunction` spectral models.  `DMFitFunction` has internal variables needed for evaluating the spectrum and the current scheme of passing the class state as a set of function arguments seemed too cumbersome.  In the new implementation the `SEDFunctor` classes own an instance of `SpectralFunction` and have an internal state for the scale and model parameters.  
The `fit_spectrum` method can now be called with either a `SEDFunctor` or `SpectralFunction` object (in the latter case a functor will be created on the fly), e.g.
```
cd = CastroData.create_from_fits('sed.fits')
fn = PowerLaw([1E-13,-2.0])
fit_out = cd.fit_spectrum(fn, [1E-13,-2.0])
``` …
> Improve CastroData fit interface

- docs/advanced/index.rst
- docs/advanced/phased.rst
- docs/config.rst
- docs/config/extension.csv
- docs/config/gtlike.csv
- docs/config/selection.csv
- docs/config/tsmap.csv
- fermipy/config.py
- fermipy/defaults.py
- fermipy/gtanalysis.py
- fermipy/sed.py
- fermipy/sourcefind.py
- fermipy/tests/test_config.py
- fermipy/tsmap.py
- fermipy/utils.py
This PR adds support for analysis with phase selections.  The following new parameters can now be defined in the configuration file:
- `gtlike.expscale` : Exposure correction applied to all sources.  The exposure will be scaled by this factor.  For phased analysis this should be set to the fractional size of the phase interval.
- `gtlike.src_expscale` : Dictionary of exposure corrections for individual sources keyed to source name.  This option overrides the exposure correction set with `gtlike.expscale` and can be used to zero the amplitude of an individual component of the model (e.g. the pulsar). 
- `selection.phasemin` : `phasemin` parameter to `gtselect`
- `selection.phasemax` : `phasemax` parameter to `gtselect`
In a typical use case one can use a single phase selection for the ON …
> Exposure correction

- docs/config/common.csv
- docs/config/residmap.csv
- docs/config/sourcefind.csv
- docs/config/tscube.csv
- docs/config/tsmap.csv
- fermipy/defaults.py
- fermipy/gtanalysis.py
- fermipy/sourcefind.py
This PR fixes a bug in `GTAnalysis.clone()` that was breaking lightcurve analysis with multiple components.  Also includes some minor improvements to the `find_sources` docstring.
> Lightcurve bugfix

- fermipy/extension.py
- fermipy/gtanalysis.py
- fermipy/irfs.py
- fermipy/ltcube.py
- fermipy/skymap.py
- fermipy/sourcefind.py
- fermipy/srcmap_utils.py
- fermipy/utils.py
This PR includes a variety of improvements to the source map generation code in fermipy:
- Fixes a bug in how the livetime histogram was being filled.
- Extracts exposures directly from binned exposure map of underlying analysis.
- New scheme for refining bin size based on PSF width and intrinsic source size.
- Option to compute sparse source maps -- i.e. skip calculation outside a certain angular distance from the source.
> Srcmap improvements

- fermipy/castro.py
- fermipy/catalog.py
- fermipy/config.py
- fermipy/diffuse/binning.py
- fermipy/diffuse/source_factory.py
- fermipy/diffuse/spectral.py
- fermipy/gtanalysis.py
- fermipy/hpx_utils.py
- fermipy/irfs.py
- fermipy/jobs/file_archive.py
- fermipy/jobs/job_archive.py
- fermipy/jobs/scatter_gather.py
- fermipy/ltcube.py
- fermipy/plotting.py
- fermipy/roi_model.py
- fermipy/skymap.py
- fermipy/spectrum.py
- fermipy/srcmap_utils.py
- fermipy/wcs_utils.py
This pull request changes some uses of staticmethod to classmethod, for the cases where the class name is used inside the method.
It's not a huge advantage, but I think there are some small advantages:
- more friendly to sub-classing, usually one want `MySubclass.create_me` to create a `MySubclass`. This is the case with `classmethod`, but not with `staticmethod` and hardcoded class name.
- less repetition of hardcoded class name inside the class -> if one ever wants to change the class name it's easier
- Using classmethod this way is the recommended pattern as far as I can tell, in all discussions of classmethod vs staticmethod for Python that I've seen. E.g. Astropy and Gammapy uses it this way.
> Use classmethod where useful

- docs/quickstart.rst
- fermipy/diffuse/catalog_src_manager.py
- fermipy/diffuse/gt_assemble_model.py
- fermipy/diffuse/gt_merge_srcmaps.py
- fermipy/diffuse/gt_srcmap_partial.py
- fermipy/diffuse/job_library.py
- fermipy/diffuse/model_manager.py
- fermipy/diffuse/residual_cr.py
- fermipy/diffuse/source_factory.py
- fermipy/gtanalysis.py
- fermipy/hpx_utils.py
- fermipy/jobs/chain.py
- fermipy/jobs/file_archive.py
- fermipy/jobs/gtlink.py
- fermipy/jobs/job_archive.py
- fermipy/jobs/scatter_gather.py
- fermipy/logger.py
- fermipy/roi_model.py
- fermipy/scripts/preprocess_data.py
- fermipy/sourcefind.py
- fermipy/tsmap.py
- fermipy/utils.py
This PR contains a few Python 3 and PEP8 print fixes. (I did a search and replace from "print " to "print", i.e. remove the space, and added `()` where necessary.)
---
Side comment: using `print` doesn't give users of Fermipy much control and IMO using logging is better (even if it's an extra two lines of boilerplate at the top). In Gammapy we never print, but always emit log messages like this: http://docs.gammapy.org/en/latest/development/howto.html#generating-log-messages
> Python 3 print fixes

- fermipy/hpx_utils.py
- fermipy/irfs.py
- fermipy/scripts/flux_sensitivity.py
- fermipy/sensitivity.py
- fermipy/tests/test_sensitivity.py
This PR makes a number of improvements to the flux sensitivity tools:
* Vectorizes integral/differential flux methods with respect to sky position.  This makes it significantly more efficient to compute sensitivity over a grid of sky positions.
* Adds sensitivity map output to `fermipy-flux-sensitivity`.  This will write HEALPix maps to the output FITS file with NSIDE set by the `nside` command-line parameter.  Maps are only computed if the `nside` parameter is defined on the command line.
* Adds support for setting independent background models for the data and model inputs to the sensitivity calculation.  By default data and model will be assumed to be equal.  The `iso_fit` and `gdiff_fit` parameters can be used to set the fit model independently.
* Various improvements to the …
> Improvements to Sensitivity Tools

- docs/advanced/sensitivity.rst
- docs/changelog.rst
- docs/model.rst
- fermipy/irfs.py
- fermipy/scripts/flux_sensitivity.py
- fermipy/sensitivity.py
- fermipy/utils.py
This PR implements support in the `fermipy-flux-sensitivity` script for calculating flux thresholds for extended sources (Disk or Gaussian).  Size and spatial morphology are set with the `spatial_size` and `spatial_model` parameters.  The calculation will still be performed for a PointSource morphology by default.
> Extended Source Sensitivity

- fermipy/defaults.py
- fermipy/gtanalysis.py
- fermipy/lightcurve.py
- fermipy/ltcube.py
- fermipy/srcmap_utils.py
This PR makes a few improvements to the lightcurve method:
- Forces recalculation of source maps for all sources within a given distance of the source of interest.  This should help improve accuracy when running with `use_scaled_srcmap=True`.
- Adds an `nthread` option which can be used to set the number of processes created when running with `multithread=True`.
- Adds columns to lightcurve output file for fit status/quality.
- Redirects logging output to separate files for each lightcurve bin.
> Lightcurve Development

- fermipy/defaults.py
- fermipy/gtanalysis.py
- fermipy/lightcurve.py
- fermipy/tests/test_gtanalysis.py
This PR includes some bug fixes and improvements for the lightcurve method:
* Fixes a bug in the implementation of the source map scaling.  Now uses the all-sky exposure map to derive scaling ratio for sources outside the ROI.
* Changes the logic for freeing parameters when fitting a time bin.  Shape parameters are only freed  if TS > `shape_ts_threshold`.
> Lightcurve Improvements

- fermipy/gtanalysis.py
This PR makes a small fix to how the ROIModel configuration was being constructed when creating a GTAnalysis instance.  This should resolve the bug reported in #158.
> Bug fix in ROIModel configuration

- fermipy/defaults.py
- fermipy/gtanalysis.py
- fermipy/ltcube.py
For lifetime cube calculation, I added the possibility to use the option to set the number of phibins. For the defaults, I added phibins = 0.
> implemented phibin > 0 support for ltcube calculation

- fermipy/castro.py
The recent update to scipy 1.0.0 in the conda defaults channel is triggering test failures due to the use of a deprecated function `scipy.stats.chisqprob` in `fermipy.castro`.  This PR replaces the deprecated function with the equivalent function from `scipy.stats.distributions`.
> Replace deprecated method in scipy.stats

- .travis.yml
- condainstall.sh
- docker/centos6-11-05-02-python/Dockerfile
- fermipy/gtanalysis.py
- fermipy/plotting.py
This PR makes some small improvements to the logic for generating parameter sequences for likelihood scans.  Now explicitly evaluates differences in log-likelihood values against the largest value obtained in the scan.  Avoids errors that were occurring when the initial parameter value was not at the peak of the likelihood function (e.g. due to fit convergence issues).  Also pinned numpy version to 1.13.3 to resolve python 2 test errors.
> Improve Parameter Sampling for Likelihood Scans

- docs/install.rst
This PR adds a section to the documentation with instructions for installing development versions.
> Add instructions for installing development versions

- .travis.yml
- condainstall.sh
- fermipy/catalog.py
- fermipy/diffuse/catalog_src_manager.py
- fermipy/plotting.py
- fermipy/skymap.py
- fermipy/tests/test_gtanalysis.py
- fermipy/utils.py
This PR resolves #189.  The ROI plotting method was referencing a weights map variable that was undefined when weighting was disabled.  Also enabled `make_plots=True` for testing `write_roi`.
> Bug fix for ROI plotting

- .travis.yml
- fermipy/castro.py
- fermipy/extension.py
- fermipy/gtanalysis.py
- fermipy/plotting.py
- fermipy/residmap.py
- fermipy/roi_model.py
- fermipy/skymap.py
- fermipy/sourcefind.py
- fermipy/sourcefind_utils.py
- fermipy/tsmap.py
- fermipy/wcs_utils.py
This PR replaces WCS and HPX map classes in `fermipy.skymap` with their equivalents from `gammapy.maps` and adds `gammapy` as a dependency.  
Note that I've left the fermipy maps modules in place for now as there are still some places where we're using the fermipy classes (e.g. in the code for LT cubes and flux sensitivity).  I'll try to make a follow-up PR to fix these as well as remove the modules with the fermipy maps code (`skymap`, `wcs_utils`, and `hpx_utils`).
Finally the HPX-related functionality will probably require some additional tweaking.  I tried to to verify that I didn't break anything with the all-sky test case analysis that @eacharles gave me but it's likely I missed something.  At some point it would be good to add a test-case for HPX-based analysis so that we can catch …
> Migrate to gammapy.maps

- .travis.yml
- docker/centos6-11-05-03-python/Dockerfile
- docker/centos6-11-07-00-python/Dockerfile
- setup.py
This PR makes a few improvements to the travis configuration:
* Minor cleanup in travis yaml file.
* Add new build against gammapy-master.  This should help us detect when/if changes in gammapy are incompatible with fermipy.  So that changes in gammapy don't block fermipy development I've marked this test as an allowed failure.
* Fixed dependency configuration in `setup.py`.  Added `gammapy` and removed `wcsaxes` (this package is no longer actively maintained since being folded into astropy).
> Add new travis builds

- fermipy/catalog.py
- fermipy/roi_model.py
This PR fixes a bug in how user-generated catalogs (i.e. those generated with `write_roi`) were being parsed when generating a new ROI model.  This adds a new catalog class which is intended for parsing catalog files generated by fermipy analyses.  I also cleaned up some of the internal logic to avoid hard-coded parameter indices.  Parameter index mapping is now setup to match that used internally by the science tools.
> Fix parsing of user-generated catalogs

- fermipy/roi_model.py
This PR fixes a bug in how the model configuration for multi-component analyses was being parsed.  Specifically when setting different diffuse template files for multiple components the template of the first component was assigned to all components.  This was due to a small typo in `ROIModel._create_diffuse_src`.
> Fix bug in parsing multi-component diffuse model configuration

- fermipy/roi_model.py
http://fermipy.readthedocs.io/en/latest/fermipy.html#module-fermipy.roi_model shows gobbled formatting. This PR fixes things.
> minor update in docstring formatting.

- .travis.yml
- travistests.sh
This adds 'sphinx' as an explicit dependency that travis should pip install for all builds.
> make sphinx an explicit requirement for travis

- fermipy/tests/test_castro.py
This PR improves the xfail in test_castro_test_spectra_yaml a bit.
This is to fix the fermipy test build fail in Gammapy:
https://travis-ci.org/gammapy/gammapy/jobs/506231818#L2682
We get a `yaml.constructor.ConstructorError`, probably because we have a different Astropy or pyyaml version.
This should make our build green again.
> Improve xfail in test_castro_test_spectra_yaml

- fermipy/extension.py
This pull request fixes an issue in the extension module when the extension fit in the energy bins is enabled with PSF scaling. Before, the `_fit_extension_ebin` call was done with `**kwargs` which broke the code since the `kwargs['psf_scale_fn']` is still the array for interpolation, but the function expects it to be a callable. Therefore, I removed the `**kwargs` from the function call and replaced it with setting the available kwargs explicitly.
> fixed _fit_extension_ebin call

- fermipy/diffuse/source_factory.py
I think I should have added 4FGL-DR2 also to the fermipy.diffuse `SourceFactory` class.
> Add 4FGL-DR2 to SourceFactory as well

- fermipy/plotting.py
Fix #399 
Fix #397 
Fix some more matplotlib related warnings (see below).
These should be gone now:
```
/Users/ich/hawc_software/miniconda3/envs/test_fermipy/lib/python3.7/site-packages/fermipy/plotting.py:148: UserWarning: Trying to register the cmap ‘ds9_b’ which already exists.
plt.register_cmap(cmap = ds9_cmap)
/Users/ich/hawc_software/miniconda3/envs/test_fermipy/lib/python3.7/site-packages/fermipy/plotting.py:304: MatplotlibDeprecationWarning: You are modifying the state of a globally registered colormap. This has been deprecated since 3.3 and in 3.6, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = mpl.cm.get_cmap(“magma”).copy()
colormap.set_under(colormap(0)) …
```
> Update interface to matplotlib

- fermipy/irfs.py
- fermipy/lightcurve.py
Adding the changes suggested by @jeget in https://github.com/fermiPy/fermipy/issues/362#issuecomment-802537434 to fix the key error referenced in many issues (#362, #411, #446, #405).
I'd like to get some input on these from @jeget and anyone who uses the lightcurve module regularly. Are these fixes enough or were you still running into issues?
> Fixes for the lightcurve issue

- fermipy/utils.py
Addresses issue #460. 
MJD reference time from [Fermi's Cicerone](https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Cicerone/Cicerone_Data/Time_in_ScienceTools.html) is used to convert MET to MJD. 
astropy.time.Time to converts the MJD from TT to UTC time scale.
A float representing MJD in UTC is returned.
In building this function, I referenced:
[gammapy.utils.time](https://docs.gammapy.org/dev/_modules/gammapy/utils/time.html) 
[PINT's "read_fits_event_mjds"](https://github.com/nanograv/PINT/blob/33fc790782958784b0078b1e74df5e19f0b82eb8/src/pint/fits_utils.py)
> modified met_to_mjd to correct issue 460

- fermipy/fits_utils.py
- fermipy/ltcube.py
- fermipy/scripts/coadd.py
- fermipy/scripts/gather_srcmaps.py
- fermipy/tsmap.py
- fermipy/validate/tools.py
- fermipy/wcs_utils.py
Changed change `clobber` -> `overwrite` in astropy fits `writeto` function everywhere (deprecated for a while, but finally enforced in astropy 5.10).
Fixes #468 .
> Compatibility with Astropy 5.10

- docs/install.rst
- environment.yml
(instead of dev label which sometimes has builds that don't work).
> Install RC fermitools from new rc label on conda

- docs/developer.rst
- docs/install.rst
- environment.yml
Update instructions to refer to release version 2.2 of the fermitools.
I aim to get fermpy 1.2 released soon once the remaining issues have been ironed out.
> Switch to release version 2.2 of fermitools

- docs/changelog.rst
- fermipy/irfs.py
- fermipy/lightcurve.py
- fermipy/skymap.py
- fermipy/sourcefind_utils.py
- fermipy/srcmap_utils.py
- fermipy/utils.py
Fix the following error in `irfs.py` which has started to show up with newer numpy (??) versions.
```
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
Also fix some more warnings before they can turn into errors.
> Fix indexing

- fermipy/plotting.py
Small bug fix but the user-supplied limits for the ROI plot were getting dropped, now they are propagated to the plot. Tested with and without transforms.
> Actually propagate vmin and vmax for ROI plot

- fermipy/extension.py
See discussion on [LAT slack](https://fermi-lat.slack.com/archives/C4ZCMN82E/p1654267228430679).
During the extension fit, the nominal extension value (from the model that the spectra were optimized on) is added to the list of extension values to scan over. This pull request changes adds an additional condition to the code to avoid scanning beyond the limits of the user-provided extension range.
> Do not scan extension values outside of user-provided range

- .github/workflows/python-package.yml
Switch to codecov-action v3 (v1 has been sunset for months).
> Update github actions

- fermipy/lightcurve.py
See discussion in #517.
Fixes #517 .
> Overwrite component-wise time selection in lightcurve bin
