fermiPy/fermipy

- .gitignore
- fermipy/__init__.py
- fermipy/config.py
- fermipy/gtanalysis.py
- fermipy/gtutils.py
- fermipy/irfs.py
- fermipy/plotting.py
- fermipy/residmap.py
- fermipy/roi_model.py
- fermipy/utils.py
- fermipy/version.py
- setup.py
Some very minor cleanup:
- add a few entries to .gitignore
- remove unused imports
- don't use "import *" (hard to figure out what comes from where)
- some first changes towards Py 2 / 3 compatible code (anticipating Python 3 Science Tools in the future :-)
These are just some edits I did while looking through the code for the first time.
I realise it's not very useful and wasn't sure if it's worth filing a PR ... feel free to just close this one!
> Minor cleanup

- docs/advanced/detection.rst
- fermipy/gtanalysis.py
- fermipy/plotting.py
If you still get the error, try deleting $HOME/.cache/matplotlib/fontList.cache and then restart the python shell and try again.
> should temporarily fix GitHub issue #19

- fermipy/__init__.py
- fermipy/castro.py
- fermipy/catalog.py
- fermipy/config.py
- fermipy/defaults.py
- fermipy/fits_utils.py
- fermipy/gtanalysis.py
- fermipy/gtutils.py
- fermipy/hpx_utils.py
- fermipy/irfs.py
- fermipy/logger.py
- fermipy/plotting.py
- fermipy/roi_model.py
- fermipy/scripts/clone_configs.py
- fermipy/scripts/cluster_sources.py
- fermipy/scripts/collect_sources.py
- fermipy/scripts/dispatch.py
- fermipy/sed_plotting.py
- fermipy/skymap.py
- fermipy/sourcefind.py
- fermipy/tsmap.py
- fermipy/utils.py
- fermipy/wcs_utils.py
Misc code cleanup pointed out by pylint.
> Misc code cleanup

- fermipy/scripts/cluster_sources.py
This PR syncs the cluster-sources script against Eric's development version.
> Sync cluster sources

- fermipy/gtanalysis.py
- fermipy/plotting.py
- fermipy/sourcefind_utils.py
- fermipy/tests/test_gtanalysis.py
- fermipy/tsmap.py
This PR fixes the missing import in `sourcefind_utils` and adds a unit test for `find_sources`.
> Add sourcefind tests

- .travis.yml
- docs/advanced/sed.rst
- docs/conf.py
- docs/config/sed.csv
- fermipy/castro.py
- fermipy/spectrum.py
We should add a Sphinx docs build on travis-ci.
I could make a PR once #51  is merged.
> Add docs build on travis-ci

- fermipy/tsmap.py
This PR implements several performance improvements for the implementation of `tsmap()`, namely:
* Newton step calculation for finding the best-fit amplitude.  In testing this was found to converge 2-3x faster than the existing root-finding method.
* Masks empty pixels and adds their contribution to the gradient and likelihood as separate terms.  This an additional factor of improvement when the counts map is very sparse.
> tsmap Performance Improvements

- fermipy/defaults.py
- fermipy/fits_utils.py
- fermipy/gtanalysis.py
- fermipy/irfs.py
- fermipy/roi_model.py
- fermipy/srcmap_utils.py
- fermipy/utils.py
This PR implements support for rescaling the PSF by an energy-dependent factor.  This functionality can be used to evaluate the impact of PSF systematics.  Also adds numpy and FITS output to `extension()`.
> New functionality for testing PSF systematics

- docs/advanced/sensitivity.rst
- fermipy/hpx_utils.py
- fermipy/irfs.py
- fermipy/roi_model.py
- fermipy/scripts/flux_sensitivity.py
- fermipy/skymap.py
- fermipy/tests/test_irfs.py
- fermipy/utils.py
- setup.py
This PR adds a new package script that calculates the LAT PS flux sensitivity.  This involved substantial updates to the `irfs` module and the addition of new methods that can be used to solve for the PS flux threshold.  `LTCube` now inherits from `HpxMap` and can be used to load an existing LT cube or create a new LT cube from scratch.  The new `Exposure` class can be used for all-sky representations of the LAT exposure.
> Sensitivity tools

- fermipy/catalog.py
- fermipy/data/models.yaml
- fermipy/gtanalysis.py
- fermipy/gtutils.py
- fermipy/model_utils.py
- fermipy/roi_model.py
- fermipy/scripts/HEALview.py
- fermipy/tests/test_roi_model.py
- fermipy/wcs_utils.py
- travistests.sh
This PR includes refactoring and bug fixes for `roi_model`.  The module is now fully isolated from the STs and can be imported without a ST installation.  Rather than querying function parameters at runtime function specifications are now maintained in `data/models.yaml`.
> ROI model updates

- fermipy/__init__.py
- fermipy/defaults.py
- fermipy/fits_utils.py
- fermipy/gtanalysis.py
- fermipy/hpx_utils.py
- fermipy/irfs.py
- fermipy/lightcurve.py
- fermipy/logger.py
- fermipy/ltcube.py
- fermipy/roi_model.py
- fermipy/skymap.py
- fermipy/tests/test_gtanalysis.py
- fermipy/tests/utils.py
- fermipy/utils.py
Bug fixes and improvements for the `lightcurve` method:
- New option for fast LT cube generation.  This is enabled by default when running the lightcurve method.
- Fixed bug related to how new sources were being handled (see #99).
> Lightcurve improvements

- fermipy/ltcube.py
- fermipy/scripts/flux_sensitivity.py
- fermipy/tests/test_sensitivity.py
- fermipy/tests/utils.py
This PR fixes several bugs in the flux sensitivity module and script and adds unit tests for the same.
> Flux sensitivity fix

- fermipy/data_struct.py
- fermipy/defaults.py
- fermipy/extension.py
- fermipy/gtanalysis.py
- fermipy/plotting.py
- fermipy/srcmap_utils.py
- fermipy/utils.py
This PR adds some features and bug fixes which are currently being tested for the extension catalog:
- Option to `extension `to fit for extension in each energy bin. 
- Improvements to `extension` plots.
- Ensure that PSF scaling function is used consistently throughout `extension`.
- Add methods to lock source parameters such that they will be ignored by free/fix methods.
> Extension Catalog Development

- fermipy/batch.py
- fermipy/hpx_utils.py
- fermipy/jobs/file_archive.py
- fermipy/jobs/job_archive.py
- fermipy/plotting.py
- fermipy/roi_model.py
- fermipy/scripts/run_tempo.py
- fermipy/skymap.py
- fermipy/tsmap.py
- fermipy/utils.py
This PR fixes undefined names as noted in #132.
> fix undefined names

- fermipy/defaults.py
- fermipy/gtanalysis.py
- fermipy/lightcurve.py
This PR makes a few tweaks to the implementation of the lightcurve method to make it more robust when analyzing crowded ROIs.  The primary change is the addition of a new parameter `max_free_sources` which sets the maximum number of sources that will be fit simultaneously with the source of interest.
> Lightcurve Development

- fermipy/data/models.yaml
- fermipy/gtutils.py
This PR updates the default bounds of the beta parameter of the LogParabola model.  This fixes an issue with the fit stability for some bright sources.
> Update default bounds for beta parameter

- fermipy/gtanalysis.py
The log is a little weird.  For some reason it includes all of the changes I've made in the dmcat-fermipy branch I pulled this change from.   The only relevant one is the "protect gtanalysis.py handling of parameter scans".   You can see that the only changes have to do with scan paramters (and an incidental fix to deep copy the HPX parameters when copying a map)
> Dmcat fix npred

- .travis.yml
- docker/centos6-11-05-03-python/Dockerfile
- docker/centos6-11-07-00-python/Dockerfile
- docker/centos6-11-07-00/Dockerfile
This PR adds a new docker configuration and tests for ST 11-07-00.
> Add tests and docker image for ST 11-07-00

- fermipy/castro.py
This just fixes a problem in computing upper limits from a castro plot.
> Merge in fix to upper limit finding from dmcat-fermipy

- docs/advanced/sensitivity.rst
- docs/model.rst
- fermipy/scripts/flux_sensitivity.py
- fermipy/sensitivity.py
- fermipy/spectrum.py
I added the LP and PLE SEDs in the flux_sensitivity.py and PL super exponential cutoff in spectrum.py
> Added new SED models for the flux sensitivity script

- docs/environment.yml
This PR fixes RTD builds by adding gammapy as a dependency.
> Fix RTD configuration

- docs/install.rst
- fermipy/diffuse/model_manager.py
- fermipy/utils.py
I added new instructions for installing Fermipy and ST with a new installation of Conda in the SLAC machines. This makes the environment independent from the version of the programs present in SLAC machines.
> Updated doc installation

- docs/advanced/sed.rst
- fermipy/scripts/dispatch.py
- fermipy/scripts/flux_sensitivity.py
I fixed an issue in flux_sensitivity.py where among the options PLExpCutoff but in the code the name PLSuperExpCutoff was used.
I also added a comment on the documentation page for the SED.
Finally I added the option -n in the script dispatch.py that permits to use more than one CPU for each job.
> Fixing an issue in flux_sensitivity.py

- fermipy/scripts/flux_sensitivity.py
I added the DM sed in the choice to calculate the flux sensitivity.
> Added DM SED in flux_sensitivity.py

- fermipy/sourcefind.py
I just fixed an error in the glon and glat error in updating the source in localization function.
> Fixed issue in the glon and glat err in localize function

- docs/changelog.rst
- fermipy/version.py
Update changelog.rst for release and tweak version.py to see lightweight tags.
> Dmcat fermipy

- docs/developer.rst
- docs/index.rst
This PR adds a new page to the documentation with instructions for creating releases.
> Add developer notes page

- docs/changelog.rst
- docs/config/common.csv
- docs/config/residmap.csv
- docs/config/source_flux_output.csv
- docs/config/source_meta_output.csv
- docs/config/source_output.csv
- docs/fermipy_diffuse.rst
- docs/fermipy_jobs.rst
- fermipy/castro.py
- fermipy/diffuse/tests/test_link_classes.py
- fermipy/jobs/analysis_utils.py
- fermipy/jobs/target_analysis.py
- fermipy/jobs/target_sim.py
- fermipy/sed_plotting.py
Adding description of the base classes in fermipy.jobs.   
Minor changes to the AnalyzeROI and AnalyzeSED classes for compatibility with the DM pipeline code.
> Minor fixes and documentation update from fermipy.jobs module.

- fermipy/diffuse/fitting.py
- fermipy/jobs/chain.py
- fermipy/jobs/link.py
- fermipy/jobs/scatter_gather.py
- fermipy/residmap.py
- setup.py
* Improve handling of resubmitting failed batch jobs
* Updated plotting in diffuse fitting.
> Minor changes for DM and diffuse analysis pipelines

- fermipy/gtanalysis.py
Slight change to fermipy/gtanalysis.py in simulate function to avoid …
> Avoid error for negative counts in gta.simulate()

- .travis.yml
- condainstall.sh
- condasetup.sh
- fake_travis.sh
- fermipy/__init__.py
- fermipy/tests/test_gtanalysis.py
- fermipy/tests/utils.py
- stinstall.sh
Updated travis testing scripts to use conda to install fermitools
> Fermipy 285

- fermipy/sourcefind.py
Small change to fermipy/sourcefind.py file.
> Mattia dev

- fermipy/gtanalysis.py
I added new functions in `gtanalysis.py` to run the the applications `gtpsf` and `gtdrm` from within fermipy for each analysis component. The functions are
- `_psf_app`
- `_drm_app`
- `compute_psf`
- `compute_drm`
The implementation is essentially equivalent to the one of the `gtsrcprob` app in the function `_srcprop_app` and `compute_srcprob`. 
This functionality is especially important for people who want to do a combined IACT and Fermi-LAT analysis with, e.g., `gammapy` which needs the DRM and PSF as an input.
> Added two functions to run gtpsf and gtdrm for each analysis component

- docs/changelog.rst
- docs/fermipy_diffuse.rst
- docs/fermipy_jobs_tools.rst
> Doc updates

- fermipy/extension.py
- fermipy/tsmap.py
This is redundant with Xan's pull request, but is being made form a branch instead of a clones repo.
> Fermipy 349 extension

- fermipy/extension.py
- fermipy/gtanalysis.py
- fermipy/residmap.py
- fermipy/tests/test_gtanalysis.py
This pull request fixes the broken residual map calculation reported in #345. It also adds an additional test so that residual map calculation with the Gaussian spatial model is checked as well.
> Fix 345 residmaps

- .travis.yml
- fake_travis.sh
- fermipy/extension.py
- fermipy/gtanalysis.py
- fermipy/lightcurve.py
- fermipy/plotting.py
- fermipy/residmap.py
- fermipy/roi_model.py
- fermipy/sourcefind.py
- fermipy/tsmap.py
- setup.py
Implemented the fixes proposed on the issue pages #369 and #372
> Fixed a couple of bugs.

- fermipy/catalog.py
- fermipy/tests/test_roi_model.py
Add 4FGL-DR2 catalog (same structure as 4FGL).
> Add 4FGL-DR2

- fermipy/jobs/slac_impl.py
- fermipy/jobs/target_collect.py
- fermipy/jobs/target_sim.py
> Dmpipe dev

- .github/workflows/python-package.yml
- environment.yml
- fermipy/irfs.py
- fermipy/jobs/job_archive.py
- fermipy/plotting.py
- fermipy/roi_model.py
- fermipy/sed.py
- fermipy/sourcefind.py
- fermipy/tests/test_gtanalysis.py
- setup.py
Includes changes implemented in #435 and #438 as well as further updates to interface with gammapy and astropy to be compatible with the latest releases. 
Tests have been changed to test against fermitools 2.1.0 release candidate.
> Fermitools210

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/data-analysis-question.md
- .github/ISSUE_TEMPLATE/feature_request.md
Adds some templates that users can pick from when opening a new issue. No changes to code.
> Adding issue templates

- environment.yml
- fermipy/lightcurve.py
- fermipy/ltcube.py
- setup.py
* Implement fix described in https://github.com/fermiPy/fermipy/issues/368#issuecomment-748549032 
* Request minimum version for matplotlib
> Lightcurve fix and pin min version of matplib

- fermipy/roi_model.py
> bugfix for exclude option in get_sources()

- docs/changelog.rst
- docs/install.rst
Minor doc updates.
Does [ci skip] even work anymore?
> Update changelog [ci skip]

- .github/ISSUE_TEMPLATE/help.md
> Update in issue templates

- fermipy/gtanalysis.py
- fermipy/lightcurve.py
@eacharles only two lines changed 😆 
1. Fixes #491 
2. Typo in `get_source_dnde`
> Tiny fixes

- .github/workflows/python-package.yml
> Update version of checkout action

- environment.yml
Pull request based on #580 with updated requirements.
> Updating fermipy to Astropy 6.0 and gammapy

- fermipy/tsmap.py
- fermipy/utils.py
Tentative fix for issues #548 and #514
> Attempt to solve the localization issue.

- .github/workflows/python-package.yml
- environment-dev.yml
- fermipy/gtanalysis.py
- fermipy/plotting.py
- fermipy/tests/test_gtanalysis.py
- fermipy/tsmap.py
- setup.py
> Fix hpx interface
